project_id = "vqudyddedeacspujotsa"

[functions.extract-form-data]
verify_jwt = true

[functions.extract-form-structure]
verify_jwt = true

[functions.send-report-email]
verify_jwt = true

[functions.send-customer-email]
verify_jwt = true

[functions.cleanup-expired-archives]
verify_jwt = false

[functions.ai-text-transform]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true
